### ISSUE TITLE
\(o_o)/  Bionic was unable to find a platform plugin named: capacitor

### ISSUE THREAD

**Issue by suryapratap** [BionicFramework/Documentation#1]
I get a "\(o_o)/  Bionic was unable to find a platform plugin named: capacitor"
when running "bionic platform add capacitor"
node -v && npx -v returns
v10.13.0
6.4.1
Python version is 2.7.15
is there anything additional that need to be checked/added

**Comment by bmsantos** [comment]
@suryapratap, you need to have ```nuget``` in the path. You can find some details here:
https://bionicframework.github.io/Documentation/0_install/#nuget

Let me know if that works for you.
