### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by FrankVDL2471** [BionicFramework/Documentation#2]
What is tht current status of this project ?

I'm looking for a (easy) way to get my Blazor Wasm PWA in the app store and this looked verry promissing.

**Comment by doyleyoung** [comment]
The project is not under active development but should still work fine.  There are a series of Youtube videos that should help you get a feel for the project -> https://www.youtube.com/user/bmrosantos . If you run into any issues, please let me know.
